namespace WebhookApp.Enums;

public enum ActionEnum
{
    None = 0,
    StartPublication = 1,
    ProcessingPublication = 10,
    RejectPublication = 11,
    EndPublication = 12,
    StartForward = 2,
    StartShare = 20,
    ProcessingShare = 21,
    RejectSharing = 22,
    ProcessingForwardByLink = 23,
    RejectForwardByLink = 24,
    EndSharing = 25,
    StartForwardByLink = 26,
    EndForwardByLink = 27,
    StartDelete = 3,
    StartDeleteLast = 30,
    EndDeleteLast = 31,
    StartDeleteByLink = 32,
    ProcessingDeleteByLink = 33,
    StartAddUser = 4,
    ProcessingAddUser = 40,
    EndAddUser = 41,
    StartDeleteUser = 5,
    ProcessingDeleteUser = 50,
    GetUserSettings = 6,
    GetUserId = 7,
    BackToMain = 8,
    Help = 9,
}